urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.views.generic import TemplateView

from lang.views import (
        Home, GoogleWebMaster, GoogleRobot, GoogleSitemap, Canvas,
        NewbieExample, ContactView, ContactCompleteView )
from lang.views.ask import (
        AskPostList, AskCorrectionList, AskPost, AskView, AskLanguageList,
        AskMyStudentList, AskUpdate, AskDelete, AskBump, CorrectionCreate)
from lang.views.correction import SentenceUpdate
from lang.views.comment import (
    CommentCreate, CommentUpdate, OverallCommentCreate, OverallCommentUpdate)
from lang.views.talk import TalkRedirection, TalkOpen, TalkSendMessage, TalkList, TalkQuit
from lang.views.ring import RingList, RingCreate, RingUpdate, RingDelete
from lang.views.quiz import QuizBookList, QuizBookUpdate, QuizBookDetail, QuizFeedback
from lang.views.invite import InviteCreate
from lang.views.point import PointList
from lang.views.poll import PollCreate
from lang.views.helps import HelpView, LegacyHelpView, StaticHelpView
from lang.views.notification import NotificationView, NotificationRead
from lang.views.bookmark import BookmarkList, BookmarkCreateOrDelete
from lang.views.topic import TopicList, TopicCreate, TopicUpdate, TopicDelete, TopicAddReader
from lang.views.privacy import PrivacyView
from lang.views.rank import WeeklyRankList, MonthlyRankList, AllRankList
from lang.views.growth import Growth, ScoreGrowth, EventGrowth


urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^googlee367e4e16cd0841d.html$',
        GoogleWebMaster.as_view(), name='google_web_master'),
    url(r'^robots.txt$', GoogleRobot.as_view(), name='google_robot'),
    url(r'^sitemap.xml$', GoogleSitemap.as_view(), name='google_sitemap'),
    url(r'^canvas/$', Canvas.as_view(), name='canvas'),
    url(r'^example/$', NewbieExample.as_view(), name='example'),

    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^thanks/$', ContactCompleteView.as_view(), name='thanks'),

) + patterns('lang.views.ask',
    url(r'^post/$', AskPost.as_view(), name='ask_post'),
    url(r'^post/(?P<pk>\d+)/$', AskView.as_view(), name='ask_view'),
    url(r'^post/(?P<pk>\d+)/correct/(?P<corrector_name>[-\.\w]+)/$',
        AskView.as_view(), name='ask_correction_view'),
    url(r'^post/(?P<pk>\d+)/bump/$', AskBump.as_view(), name='ask_bump'),
    url(r'^post/(?P<pk>\d+)/update/$', AskUpdate.as_view(), name='ask_update'),
    url(r'^post/(?P<pk>\d+)/delete/$', AskDelete.as_view(), name='ask_delete'),

    url(r'^post/(?P<pk>\d+)/correction/$', CorrectionCreate.as_view(),
        name='correction_create'),

    url(r'^user/(?P<screen_name>[-\.\w]+)/$', 
        AskPostList.as_view(), name='ask_post_list'),
    url(r'^user/(?P<screen_name>[-\.\w]+)/post/$', 
        AskPostList.as_view(), name='ask_post_list'),
    url(r'^user/(?P<screen_name>[-\.\w]+)/correction/$', 
        AskCorrectionList.as_view(), name='ask_correction_list'),

    url(r'^language/$', AskLanguageList.as_view(), name='ask_language_list'),
    url(r'^language/(?P<language>[-\w]+)/$', 
        AskLanguageList.as_view(), name='ask_language_list'),
    url(r'^mystudents/$', AskMyStudentList.as_view(), name='ask_student_list'),

) + patterns('lang.views.sentence',
    url(r'^sentence/(?P<pk>\d+)/update/$',
        SentenceUpdate.as_view(), name='sentence_update'),

) + patterns('lang.views.comment',
    url(r'^comment/create/$', CommentCreate.as_view(), name='comment_create'),
    url(r'^comment/(?P<pk>\d+)/update/$', CommentUpdate.as_view(), name='comment_update'),
    url(r'^overall_comment/create/$',OverallCommentCreate.as_view(), name='overall_comment_create'),
    url(r'^overall_comment/(?P<pk>\d+)/update/$', OverallCommentUpdate.as_view(), name='overall_comment_update'),

) + patterns('lang.views.talk',
    url(r'^talk/$', TalkList.as_view(), name='talk_list'),
    url(r'^talk/searchroom/$', TalkRedirection.as_view(), name='search_chatroom'),
    url(r'^talk/send/$', TalkSendMessage.as_view(), name='send_chat_message'),
    url(r'^talk/open/(?P<pk>\d+)/$', TalkOpen.as_view(), name='open_chatroom'),
    url(r'^talk/quit/(?P<pk>\d+)/$', TalkQuit.as_view(), name='quit_chatroom'),

) + patterns('lang.views.ring',
    url(r'^ring/$', RingList.as_view(), name='ring_list'),
    url(r'^ring/create/$', RingCreate.as_view(), name='ring_create'),
    url(r'^ring/(?P<pk>\d+)/update/$', RingUpdate.as_view(), name='ring_update'),
    url(r'^ring/(?P<pk>\d+)/delete/$', RingDelete.as_view(), name='ring_delete'),

) + patterns('lang.views.quiz',
    url(r'^user/(?P<screen_name>[-\.\w]+)/quiz/$', 
        QuizBookList.as_view(), name='quizbook_list'),
    url(r'^user/(?P<screen_name>[-\.\w]+)/quiz/(?P<date>\d{4}-\d{2}-\d{2}(-\d+)?)/$', 
        QuizBookUpdate.as_view(), name='quizbook_update'),
    url(r'^user/(?P<screen_name>[-\.\w]+)/quiz/(?P<date>\d{4}-\d{2}-\d{2}(-\d+)?)/result/$',
        QuizBookDetail.as_view(), name='quizbook_detail'),
    url(r'^quiz/(?P<pk>\d+)/feedback/$', QuizFeedback.as_view(), name='quiz_feedback'),

) + patterns('lang.views.point',
    url(r'^user/(?P<screen_name>[-\.\w]+)/points/$', 
        PointList.as_view(), name='point_list'),

) + patterns('lang.views.invite',
    url(r'^user/(?P<screen_name>[-\.\w]+)/invite/add/$',
        InviteCreate.as_view(), name='invite_add'),
    #url(r'^user/(?P<screen_name>[-\.\w]+)/invites/$',
    #    InviteList.as_view(), name='invite'),

) + patterns('lang.views.invite',
    url(r'^user/(?P<screen_name>[-\.\w]+)/growth/$', Growth.as_view(), name='growth'),
    url(r'^user/(?P<pk>\d+)/growth/score/$', ScoreGrowth.as_view(), name='score_of_growth'),
    url(r'^user/(?P<pk>\d+)/growth/event/$', EventGrowth.as_view(), name='event_of_growth'),

) + patterns('lang.views.poll',
    url(r'^poll/(?P<event_id>\d+)/$', 
        PollCreate.as_view(), name='poll_create'),

) + patterns('lang.views.helps',
    url(r'^help/$', HelpView.as_view(), name='helps'),

    url(r'^help/what-can-i-write-about/$',
        TemplateView.as_view(template_name="lang/help/post/about.html"),
        name='helps_post_about'),
    url(r'^help/what-will-happen-after-i-write-a-post/$',
        TemplateView.as_view(template_name="lang/help/post/will_happen.html"),
        name='helps_post_will_happen'),
    url(r'^help/i-want-to-learn-more-than-two-foreign-languages/$',
        TemplateView.as_view(template_name="lang/help/post/more_language.html"),
        name='helps_post_more_language'),

    url(r'^help/(?P<slug>[\w-]+)/$', StaticHelpView.as_view(), name='static_helps'),
    # below urls are legacy
    url(r'^help/(?P<pk>\d+)/$', LegacyHelpView.as_view(), name='helps'),

) + patterns('lang.views.notification',
    url(r'^notifications/$', NotificationView.as_view(), name='notifications'),
    url(r'^notifications/(?P<pk>\d+)/$',
        NotificationRead.as_view(), name='notification_update'),

) + patterns('lang.views.bookmark',
    url(r'^user/(?P<screen_name>[-\.\w]+)/notes/$', 
        BookmarkList.as_view(), name='bookmark_list'),
    url(r'^notes/create_or_delete/$', BookmarkCreateOrDelete.as_view(),
        name='bookmark_create_or_delete')

) + patterns('lang.views.bookmark',
    url(r'^rank/$', AllRankList.as_view(), name='all_rank'),
    url(r'^rank/weekly/$', WeeklyRankList.as_view(), name='weekly_rank'),
    url(r'^rank/monthly/$', MonthlyRankList.as_view(), name='monthly_rank')

) + patterns('lang.views.topic',
    url(r'^topics/(?P<language>[-\w]+)/$', 
        TopicList.as_view(), name='topic_list'),
    url(r'^topics/(?P<language>[-\w]+)/create/$', 
        TopicCreate.as_view(), name='topic_create'),
    url(r'^topics/(?P<language>[-\w]+)/(?P<pk>\d+)/update/$', 
        TopicUpdate.as_view(), name='topic_update'),
    url(r'^topics/(?P<language>[-\w]+)/(?P<pk>\d+)/delete/$', 
        TopicDelete.as_view(), name='topic_delete'),
    url(r'^topics/(?P<language>[-\w]+)/(?P<pk>\d+)/read/$', 
        TopicAddReader.as_view(), name='topic_add_reader'),

) + patterns('lang.views.legal',
    url(r'^privacy/$', PrivacyView.as_view(), name='privacy'),

) + patterns('',
    url(r'^%s(.*)$' % settings.MEDIA_URL[1:],
        'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }, 'static'),
)

forms.py
# -*- coding: utf-8 -*-

from django.utils.translation import ugettext_lazy
from django import forms

from lang.models import Ask

class AskForm(forms.ModelForm):
    title = forms.CharField()
    context = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Ask
        exclude = (
                'user',
                'ip_addr',
                'original_context',
                'language',
                )

    def __init__(self, user, *args, **kwargs):
        super(AskForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['title', 'context', 'topic']

        language = user.get_learning_language().get_name_display().capitalize()

        for field_name in self.fields:
            field = self.fields.get(field_name)
            field.widget.attrs['class'] = 'input-block-level'

        title = self.fields.get('title')
        title.label = ""
        title.required = False
        title.widget.attrs['placeholder'] = ugettext_lazy('Title')

        context = self.fields.get('context')
        context.label = ""
        context.widget.attrs['rows'] = '7'
        context.widget.attrs['placeholder'] =  \
                ugettext_lazy("Write about events, experiences, likes, dislikes, hobbies, or anything else that's on your mind!")

        topic = self.fields.get('topic')
        topic.label = ""
        topic.required = False
        topic.widget = forms.HiddenInput()

views/correction.py
# -*- coding: utf-8 -*-
from datetime import datetime
from diff_match_patch import *

from django import forms
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.views.generic import FormView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.db import transaction

from lang.models import Correction, Sentence
from lang.views import JSONResponseMixin
from lang.mail import LingRingMailman


class SentenceForm(forms.ModelForm):

    class Meta:
        model = Sentence
        exclude = ('user', 'ip_addr', 'type', 'ask', 'correction',
                'type', 'parent', 'native_context', 'tags')


class SentenceUpdate(JSONResponseMixin, UpdateView):
    model = Sentence
    form_class = SentenceForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(SentenceUpdate, self).dispatch(
                request, *args, **kwargs)

    def form_invalid(self, form):
        context = {}
        context.update({
            'status': 'error'
            })
        if self.request.is_ajax():
            return JSONResponseMixin.render_to_response(
                self, context)
        else:
            return super(SentenceUpdate, self).form_invalid(form)

    def form_valid(self, form):
        sentence = form.save(commit=False)

        dmp = diff_match_patch()
        dmp.Diff_EditCost=1
        d = dmp.diff_main(sentence.parent.context, sentence.context)
        dmp.diff_cleanupEfficiency(d)
        html_context = dmp.diff_prettyHtml(d)
        sentence.html_context = html_context
        sentence.save()

        context = {}
        if sentence.context == '[Perfect]':
            comment = \
                '<img src="' + settings.STATIC_URL + 'image/ic_perfect.png' + '" />'
        elif sentence.context == '[Do-not-understand]':
            comment = \
                '<img src="' + settings.STATIC_URL + 'image/ic_dontunderstand.png' + '" />'
        else:
            comment = html_context

        context.update({
            'status': 'success',
            'comment': comment,
            'value': sentence.context,
            })
        return JSONResponseMixin.render_to_response(self, context)

views/topic.py
import json

from datetime import datetime

from django import forms
from django.http import Http404
from django.db import transaction
from django.db.models import Q
from django.shortcuts import render_to_response, get_object_or_404
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView, FormView
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.template import RequestContext
from django.utils.translation import ugettext_lazy
from django.utils.decorators import method_decorator

from lang.models import Topic, UserProfile, Language
from lang.views import LangExtraContext, MessageMixin, AuthorRequiredMixin, JSONResponseMixin
from lang.decorators import staff_required


class TopicList(ListView, LangExtraContext):
    model = Topic
    context_object_name = 'topics'
    template_name = 'lang/topic/list.html'
    paginate_by = 10

    def dispatch(self, request, *args, **kwargs):
        return super(TopicList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(TopicList, self).get_queryset()
        language = get_object_or_404(Language, name=self.kwargs['language'], )
        queryset = queryset.filter(language=language)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(TopicList, self).get_context_data(**kwargs)
        context.update({
            'language': self.kwargs['language'],
            'ask_of_topics': self.request.user.ask_set.filter(
                topic__in=self.get_queryset()).values_list('topic__id', flat=True)
            })
        return context


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        exclude = ('user', 'language', 'ip_addr', )


class TopicCreate(CreateView, LangExtraContext, MessageMixin):
    model = Topic
    form_class = TopicForm
    template_name='lang/topic/list.html'
    success_message = "Correction Submit Successfully"

    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TopicCreate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(TopicCreate, self).get_context_data(**kwargs)
        context['language']=self.kwargs['language']
        return context

    def form_invalid(self, form):
        messages.set_level(self.request, messages.ERROR)
        messages.error(self.request, "%s" % form.errors)
        return HttpResponseRedirect(reverse('topic_list', args=(self.kwargs['language'], )))

    def form_valid(self, form):
        user = self.request.user
        topic = form.save(commit=False)
        topic.user = user
        topic.language = user.get_native_language()
        topic.save()

        messages.success(self.request, self.success_message)
        return super(TopicCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('topic_list', args=(self.kwargs['language'],))


class TopicUpdate(UpdateView, AuthorRequiredMixin, LangExtraContext, MessageMixin):
    model = Topic
    form_class = TopicForm
    context_object_name = 'topic'
    template_name='lang/topic/edit.html'
    success_message = "Update Submit Successfully"

    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TopicUpdate, self).dispatch(request, *args, **kwargs)

    def form_invalid(self, form):
        messages.set_level(self.request, messages.ERROR)
        messages.error(self.request, "%s" % form.errors)
        return HttpResponseRedirect(reverse('topic_list', args=(self.kwargs['language'], )))

    def form_valid(self, form):
        user = self.request.user
        topic = form.save(commit=False)
        topic.user = user
        topic.language = user.get_native_language()
        topic.save()

        messages.success(self.request, self.success_message)

        return HttpResponseRedirect(reverse('topic_list', args=(self.kwargs['language'],)))


class TopicDelete(DeleteView, AuthorRequiredMixin):
    model = Topic

    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TopicDelete, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('topic_list', args=(self.kwargs['language'],))


class TopicAddReader(JSONResponseMixin, UpdateView):
    model = Topic

    def dispatch(self, request, *args, **kwargs):
        return super(TopicAddReader, self).dispatch(request, *args, **kwargs)

    def post(self, *args, **kwargs):
        try:
            topic = self.get_object()
            user = self.request.user
            topic.reader.add(user)
            context = {
                'status': 'success',
                'topic': False
                }
            if user.has_unread_topics():
                topic = user.unread_topics()[0]
                context.update({
                    'topic': True,
                    'id': topic.id,
                    'title': topic.title,
                    'author': topic.user.screen_name,
                    'author_language': topic.language.name,
                    'add_reader_url': reverse('topic_add_reader', args=(topic.language.name, topic.id,))
                    })
            else:
                context.update({
                    'topic_list_url': reverse('topic_list', args=(user.get_learning_language().name,))
                    })
            return JSONResponseMixin.render_to_response(self, context)
        except:
            raise Http404

templates/lang/ask/_edit_sentence.html
{% load i18n %}

<div class="originalSentenceLine">
  <div class="sentence-wrapper">
    <div class="bold original-sentence child-no-bg">
      <textarea name="{% if is_title %}t{% endif %}l_{{ sentence.id }}" type="text" placeholder="{% trans 'Sentence deleted.' %}" class="correction_form lc">{{ sentence.context }}</textarea>
    </div>
    {% if not sentence.native_context %}
    <div class="add-translation-wrapper">
      <span>{% trans 'Add a description' %}</span>
    </div>
    {% endif %}

    <div class="original-sentence child-no-bg native-sentence-wrapper {% if not sentence.native_context %}hide{% endif %}">
      <textarea name="{% if is_title %}t{% endif %}n_{{ sentence.id }}" type="text" placeholder="{% trans 'Give context in your native language.' %}" class="correction_form">{{ sentence.native_context|default:"" }}</textarea>
    </div>
  </div>
</div>

templates/lang/ask/_journal_tab.html
{% load i18n %}

<ul class="nav nav-tabs nav-justified navJournal">
  <li {% ifequal nav_me 'post' %}class="active"{% endifequal %}>
    <a href="{% url 'ask_post_list' profile_user.screen_name %}">
      {% if user == profile_user %}
      {{ profile_user.get_learning_language }} {% trans 'Learning' %}
      <span id="my_post_badge" class="badge badge-important {% if not user.get_my_notifications.exists %}hide{% endif %}">{{ user.get_my_notifications.count }}</span>
      {% else %}
      {{ profile_user.get_learning_language }}
      {% endif %}
      <div class="numberInfo text-info"><strong> {{ profile_user.get_post_count }}</strong></div>
    </a>
  </li>

  <li {% ifequal nav_me 'correction' %}class="active"{% endifequal %}>
  <a href="{% url 'ask_correction_list' profile_user.screen_name %}">
  {% if user == profile_user %}
  {{ profile_user.get_native_language }} {% trans 'Correction' %}
  <span id="my_post_badge" class="badge badge-important {% if not user.get_other_post_notifications.exists %}hide{% endif %}">{{ user.get_other_post_notifications.count }}</span>
  {% else %}
  {{ profile_user.get_native_language }}
  {% endif %}
  <div class="numberInfo text-info"><strong>{{ profile_user.get_correction_count }}</strong></div>
  </a></li>
</ul>

{% if nav_me == 'post' and user == profile_user %}
  <div id="listOption">
      <label class="radio inline">
          <input data-url="{% url 'ask_post_list' profile_user.screen_name %}" type="radio" name="radio_link" class="radio_link" {% if not request.GET.order %}checked{% endif %}>
          {% trans 'Latest Notification' %}
      </label>

      <label class="radio inline">
          <input data-url="{% url 'ask_post_list' profile_user.screen_name %}?order=post" type="radio" name="radio_link" class="radio_link" {% ifequal request.GET.order 'post' %}checked{% endifequal %}>
          {% trans 'Latest Post' %}
      </label>
  </div>
{% endif %}

templates/lang/ask/_topic.html
{% load i18n %}

{% if not user.is_authenticated or user != profile_user %}
{% else %}
  {% if user.has_unread_topics %}
  {% with user.unread_topics.0 as topic %}
  <div class="topicBox">
    {% with topic.user as topic_author and topic.title as title and topic.language.name|capfirst as topic_language %}
    <h5>LingRing's Topic Suggestion</h5>
    <blockquote>
        <h5 class="topic-title">"{{ title }}"</h5>
        <small><a href="{% url 'ask_post_list' topic.user.screen_name %}"><span class="topic-author">{{ topic_author }}</span></a>, the <span class="topic-author-language">{{ topic_language }}</span> Master of LingRing</small>
    </blockquote>
    {% endwith %}
    <div class="text-right topic-action">
        <a id="create-topic-btn" href="#" data-toggle="modal" data-target="#modal-post" data-title="{{ topic.title }}" data-id="{{ topic.id }}">
          <small><i class="fa fa-edit"></i> {% trans 'Write Now' %}</small>
        </a>

        <form id="topic-read-form" action="{% url 'topic_add_reader' topic.language.name topic.id %}" method="post">{% csrf_token %}
          <button type="submit" class="btn btn-link">
              <small><i class="fa fa-eraser"></i><span style="vertical-align:text-top"> {% trans 'Ignore' %}</span></small>
          </button>
        </form>

        <a href="{% url 'topic_list' user.get_learning_language.name %}">
          <small><i class="fa fa-list"></i> {% trans 'See More Topics' %}</small>
        </a>
    </div>
  </div>

  <div id="no-unread-topic" class="text-right topicBox hidden">
    <a href="{% url 'topic_list' user.get_learning_language.name %}">
      <small><i class="fa fa-list"></i> {% trans 'See Topics' %}</small>
    </a>
  </div>

  {% endwith %}
  {% elif user.get_learning_language.topic_set.exists %}
  <div class="text-right topicBox">
    <a href="{% url 'topic_list' user.get_learning_language.name %}" class="create-topic-link">
      <small><i class="fa fa-list"></i> {% trans 'See Topics' %}</small>
    </a>
  </div>
  {% endif %}
{% endif %}

templates/lang/ask/post.html
{% extends 'base.html' %}
{% load i18n staticfiles compress  bootstrap_toolkit %}

{% block title %} | Your First Post{% endblock %}

{% block body_header %}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="menus">
            <a href="#" class="brand">{% block brand-name %}{% trans 'Writing on LingRing' %}{% endblock %}</a>
        </div>
    </div>
</div>
{% endblock %}

<div class="container">
    <div id="content"> 
    {% block contents %}

    <h4 id="firstWriting" class="text-center">
    {% blocktrans with user.get_learning_language as learning_language %}
    Write Your First {{ learning_language }} Post
    {% endblocktrans %}
    </h4>
    <div class="pull-right text-right">
        <div class="firstPostHelpLink"><a href="{% url 'helps_post_about' %}">{% trans 'What do I write about?' %}</a></div>
        <div class="clear firstPostHelpLink"><a href="{% url 'helps_post_will_happen' %}">{% blocktrans with user.get_learning_language as learning_language %} I don't know how to write in {{ learning_language }}!{% endblocktrans %}</a></div>
    </div>
    <form id="firstPost" action="{% url 'ask_post' %}" method="post" class="form-horizontal">
    {% csrf_token %}
        <input type="hidden" name="first_post" value="true" />

        <div class="control-group postInputBox">
            <input type='text' name='title' class="span6" placeholder="{% trans 'Title' %}" value="{{ form.title.value|default:'' }}"/>
        </div>

        <div class="control-group postInputBox">
            {% with form.context.value|default:'' as context_val %}
            <textarea id="id_context" name='context' class="span6" placeholder="{% trans 'Write about your day.' %}" rows="10">{{ context_val }}</textarea> 
            <div class="pull-right text-counter">(<span class="current-text">{{ context_val|length }}</span>/<span>15</span>)</div>
            <div class="clearfix"></div>

            {% if form.context.errors %}
            {{ form.context.errors }}
            {% else %}
            <ul class="text-info unstyled">
                <li>{% trans 'Requires more than 15 letters.' %}</li>
            </ul>
            {% endif %}
            {% endwith %}
        </div>

        <!--div class="firstPostHelpLink"><a href="{% url 'helps_post_will_happen' %}">{% trans 'What will happen after I write a post?' %}</a></div-->
        <div class="firstPostHelpLink"><a href="{% url 'helps_post_more_language' %}">{% trans 'I want to learn more than two languages!' %}</a></div>

        <div class="control-group">
            <div class="controls">
                <div class="controlButtonAtBottom">
                    <button id="firstPostSubmit" type="submit" data-gac="PostActivation" data-gan="First Post" class="btn btn-default right gaevent">{% trans 'Done' %}</button>
                    <button type="button" data-gac="PostActivation" data-gan="First Post Skip" class="btn btn-default right gaevent">{% trans 'Skip' %}</button>
                </div>
            </div>
        </div>
    </form>

    {% include 'lang/modal/blank_post.html' %}
    {% include 'lang/modal/shorten_post.html' %}
    {% endblock %}

    </div>
</div>

{% block javascript %}
{{ block.super }}

{% compress js %}
<script type="text/javascript">
$(document).on("submit", "#firstPost", function () {
    $f = $(this);
    var title = $f.find('input[name="title"]').val();
    var context = $f.find('textarea[name="context"]').val();
    if (!title && !context) {
        $('#modal-blank-post').modal();
        return false;
    }
    else if (context.length < 15) {
        $('#modal-shorten-post').modal();
        return false;
    }

    $f.find("#firstPostSubmit").attr('disabled', true);
});

$(document).on("keyup", "#firstPost textarea", function () {
    var context_length = $(this).val().length
    var $submit_btn = $("#firstPostSubmit");
    var $counter = $(".text-counter");
    $(".current-text").text(context_length);

    if ( context_length >= 15) {
      $submit_btn.addClass('btn-primary');
      $counter.addClass("text-success").removeClass("text-error");
    } else {
      $submit_btn.removeClass('btn-primary');
      $counter.addClass("text-error").removeClass("text-success");
    }
})

$(document).ready(function() {
  $('#modal-blank-post').on("hidden", function () {
    $("#firstPostSubmit").attr('disabled', false);
  });

  $('#modal-shorten-post').on("hidden", function () {
    $("#firstPostSubmit").attr('disabled', false);
  });

  if($("#id_context").val().length < 15) {
    $(".text-counter").addClass("text-error").removeClass("text-success");
  } else {
    $(".text-counter").addClass("text-success").removeClass("text-error");
  }

});
</script>
{% endcompress %}
{% endblock %}